import type { MenuItem, GalleryImage } from "@/types";

// Menu Items
export const menuItems: MenuItem[] = [
  // Hot Coffee
  {
    id: "1",
    name: "Signature Espresso",
    description: "Rich, bold espresso with notes of dark chocolate and caramel",
    price: 4.50,
    category: "hot-coffee",
    isPopular: true,
  },
  {
    id: "2",
    name: "Arabica Pour Over",
    description: "Single-origin hand-poured coffee with floral undertones",
    price: 5.50,
    category: "hot-coffee",
    isNew: true,
  },
  {
    id: "3",
    name: "Classic Cappuccino",
    description: "Perfectly balanced espresso with silky steamed milk foam",
    price: 5.00,
    category: "hot-coffee",
    isPopular: true,
  },
  {
    id: "4",
    name: "Vanilla Latte",
    description: "Smooth espresso with vanilla and creamy steamed milk",
    price: 5.50,
    category: "hot-coffee",
  },
  {
    id: "5",
    name: "Mocha Delight",
    description: "Espresso, chocolate, and steamed milk topped with whipped cream",
    price: 6.00,
    category: "hot-coffee",
  },
  {
    id: "6",
    name: "Turkish Coffee",
    description: "Traditional finely ground coffee, unfiltered and aromatic",
    price: 5.00,
    category: "hot-coffee",
  },
  // Cold & Iced Coffee
  {
    id: "7",
    name: "Classic Cold Brew",
    description: "Slow-steeped for 20 hours, smooth and refreshing",
    price: 5.00,
    category: "cold-iced-coffee",
    isPopular: true,
  },
  {
    id: "8",
    name: "Iced Americano",
    description: "Double shot espresso over ice with cold water",
    price: 4.50,
    category: "cold-iced-coffee",
  },
  {
    id: "9",
    name: "Iced Vanilla Latte",
    description: "Espresso, vanilla syrup, and cold milk over ice",
    price: 5.50,
    category: "cold-iced-coffee",
  },
  {
    id: "10",
    name: "Iced Caramel Macchiato",
    description: "Layered espresso with caramel drizzle over iced milk",
    price: 6.00,
    category: "cold-iced-coffee",
    isNew: true,
  },
  // Smoothies
  {
    id: "11",
    name: "Berry Blast Smoothie",
    description: "Mixed berries, banana, and yogurt blended to perfection",
    price: 6.00,
    category: "smoothies",
    isPopular: true,
  },
  {
    id: "12",
    name: "Tropical Mango Smoothie",
    description: "Fresh mango, pineapple, and coconut milk",
    price: 6.00,
    category: "smoothies",
  },
  {
    id: "13",
    name: "Green Power Smoothie",
    description: "Spinach, banana, apple, and ginger for a healthy boost",
    price: 6.50,
    category: "smoothies",
    isNew: true,
  },
  // Blended Coffee
  {
    id: "14",
    name: "Mocha Frappé",
    description: "Blended espresso with chocolate, milk, and ice topped with cream",
    price: 6.00,
    category: "blended-coffee",
    isPopular: true,
  },
  {
    id: "15",
    name: "Caramel Coffee Frappé",
    description: "Smooth blended coffee with caramel swirl and whipped cream",
    price: 6.00,
    category: "blended-coffee",
  },
  {
    id: "16",
    name: "Vanilla Bean Frappé",
    description: "Creamy blended vanilla with espresso and crushed ice",
    price: 6.00,
    category: "blended-coffee",
  },
  // Coffee Alternatives
  {
    id: "17",
    name: "Chai Tea Latte",
    description: "Spiced chai blend with warm steamed milk",
    price: 5.00,
    category: "coffee-alternatives",
    isPopular: true,
  },
  {
    id: "18",
    name: "Hot Chocolate",
    description: "Rich Belgian chocolate with whipped cream",
    price: 4.50,
    category: "coffee-alternatives",
  },
  {
    id: "19",
    name: "Golden Turmeric Latte",
    description: "Warming turmeric, ginger, and honey with steamed milk",
    price: 5.00,
    category: "coffee-alternatives",
    isNew: true,
  },
  {
    id: "20",
    name: "Lavender Honey Milk",
    description: "Steamed milk infused with lavender syrup and local honey",
    price: 5.00,
    category: "coffee-alternatives",
  },
  // Healthy Breakfast
  {
    id: "21",
    name: "Açaí Bowl",
    description: "Blended açaí topped with granola, banana, and fresh berries",
    price: 8.00,
    category: "healthy-breakfast",
    isPopular: true,
  },
  {
    id: "22",
    name: "Avocado Toast",
    description: "Sourdough toast with smashed avocado, seeds, and chili flakes",
    price: 7.00,
    category: "healthy-breakfast",
  },
  {
    id: "23",
    name: "Overnight Oats",
    description: "Creamy oats with chia seeds, honey, and seasonal fruit",
    price: 6.00,
    category: "healthy-breakfast",
    isNew: true,
  },
  {
    id: "24",
    name: "Granola & Yogurt Parfait",
    description: "Layers of Greek yogurt, house granola, and mixed berries",
    price: 6.50,
    category: "healthy-breakfast",
  },
  // Matcha
  {
    id: "25",
    name: "Classic Matcha Latte",
    description: "Premium ceremonial-grade Japanese matcha with steamed milk",
    price: 5.50,
    category: "matcha",
    isPopular: true,
  },
  {
    id: "26",
    name: "Iced Matcha Latte",
    description: "Chilled matcha with your choice of milk over ice",
    price: 5.50,
    category: "matcha",
  },
  {
    id: "27",
    name: "Matcha Frappé",
    description: "Blended matcha with milk and ice, topped with cream",
    price: 6.00,
    category: "matcha",
    isNew: true,
  },
  // Ice Cream
  {
    id: "28",
    name: "Affogato",
    description: "Vanilla gelato drowned in a shot of hot espresso",
    price: 6.50,
    category: "ice-cream",
    isPopular: true,
  },
  {
    id: "29",
    name: "Coffee Ice Cream Scoop",
    description: "Rich house-made coffee ice cream, single or double scoop",
    price: 4.00,
    category: "ice-cream",
  },
  {
    id: "30",
    name: "Matcha Ice Cream Scoop",
    description: "Creamy matcha-flavored ice cream made in-house",
    price: 4.00,
    category: "ice-cream",
    isNew: true,
  },
  // Water
  {
    id: "31",
    name: "Still Water",
    description: "Purified still water, served chilled",
    price: 2.00,
    category: "water",
  },
  {
    id: "32",
    name: "Sparkling Water",
    description: "Refreshing sparkling mineral water",
    price: 3.00,
    category: "water",
  },
  {
    id: "33",
    name: "Infused Water",
    description: "Cucumber-mint or lemon-ginger infused water",
    price: 3.50,
    category: "water",
    isNew: true,
  },
  // Fresh Juice
  {
    id: "34",
    name: "Fresh Orange Juice",
    description: "Hand-squeezed orange juice, no added sugar",
    price: 5.00,
    category: "fresh-juice",
    isPopular: true,
  },
  {
    id: "35",
    name: "Green Detox Juice",
    description: "Celery, cucumber, apple, and lemon pressed fresh",
    price: 6.00,
    category: "fresh-juice",
    isNew: true,
  },
  {
    id: "36",
    name: "Carrot Ginger Juice",
    description: "Fresh carrot with a kick of ginger and a squeeze of lemon",
    price: 5.50,
    category: "fresh-juice",
  },
  // Bakery Products
  {
    id: "37",
    name: "Butter Croissant",
    description: "Flaky, golden French croissant baked fresh daily",
    price: 3.50,
    category: "bakery",
    isPopular: true,
  },
  {
    id: "38",
    name: "Almond Danish",
    description: "Sweet pastry with almond cream and sliced almonds",
    price: 4.00,
    category: "bakery",
  },
  {
    id: "39",
    name: "Blueberry Muffin",
    description: "Moist muffin bursting with fresh blueberries",
    price: 3.50,
    category: "bakery",
  },
  {
    id: "40",
    name: "Chocolate Éclair",
    description: "Choux pastry filled with cream, topped with chocolate",
    price: 4.50,
    category: "bakery",
    isNew: true,
  },
  {
    id: "41",
    name: "Cinnamon Roll",
    description: "Warm, gooey cinnamon roll with cream cheese glaze",
    price: 4.00,
    category: "bakery",
  },
];

// Gallery Images
export const galleryImages: GalleryImage[] = [
  // ── The Café ──
  {
    id: "1",
    src: "/images/IMG_2057.JPG.jpeg",
    alt: "Seating area with tables, plants, and warm atmosphere",
    width: 4032,
    height: 3024,
    category: "cafe",
  },
  {
    id: "2",
    src: "/images/IMG_2024.JPG.jpeg",
    alt: "Front counter with La Cimbali espresso machine and pastry display",
    width: 4032,
    height: 3024,
    category: "cafe",
  },
  {
    id: "3",
    src: "/images/IMG_2036.JPG.jpeg",
    alt: "Lounge area with leather sofas and wooden accents",
    width: 4032,
    height: 3024,
    category: "cafe",
  },
  {
    id: "4",
    src: "/images/IMG_2035.JPG.jpeg",
    alt: "Counter with track lighting and branding",
    width: 3024,
    height: 4032,
    category: "cafe",
  },
  {
    id: "5",
    src: "/images/IMG_2067.JPG.jpeg",
    alt: "Counter with pendant lights",
    width: 4032,
    height: 3024,
    category: "cafe",
  },
  {
    id: "6",
    src: "/images/IMG_2058.JPG.jpeg",
    alt: "Wide interior view with seating and counter",
    width: 4032,
    height: 3024,
    category: "cafe",
  },
  {
    id: "7",
    src: "/images/IMG_2029.JPG.jpeg",
    alt: "Counter with ambient lighting",
    width: 4032,
    height: 3024,
    category: "cafe",
  },
  {
    id: "8",
    src: "/images/IMG_2078.JPG.jpeg",
    alt: "Pastry display with fresh baked goods",
    width: 4032,
    height: 3024,
    category: "cafe",
  },
  {
    id: "9",
    src: "/images/IMG_2037.JPG.jpeg",
    alt: "Lounge seating with sofas and natural light",
    width: 4032,
    height: 3024,
    category: "cafe",
  },
  {
    id: "10",
    src: "/images/IMG_2062.JPG.jpeg",
    alt: "Bar area with La Cimbali machine and balcony light",
    width: 4032,
    height: 3024,
    category: "cafe",
  },
  {
    id: "11",
    src: "/images/gallery/shop-counter-2.webp",
    alt: "Counter at night with warm glow",
    width: 900,
    height: 1200,
    category: "cafe",
  },
  {
    id: "12",
    src: "/images/interior.png",
    alt: "Interior with lounge seating and counter view",
    width: 3024,
    height: 4032,
    category: "cafe",
  },
  // ── The Academy ──
  {
    id: "13",
    src: "/images/IMG_2073.JPG.jpeg",
    alt: "Barista Coffee School with professional espresso machines",
    width: 4032,
    height: 3024,
    category: "academy",
  },
  {
    id: "14",
    src: "/images/IMG_2068.JPG.jpeg",
    alt: "Barista Coffee School training station",
    width: 4032,
    height: 3024,
    category: "academy",
  },
  {
    id: "15",
    src: "/images/IMG_2074.JPG.jpeg",
    alt: "SCA certifications and credentials on display",
    width: 4032,
    height: 3024,
    category: "academy",
  },
  {
    id: "16",
    src: "/images/IMG_2069.JPG.jpeg",
    alt: "Inside the Barista Coffee School",
    width: 4032,
    height: 3024,
    category: "academy",
  },
  // ── The Building ──
  {
    id: "17",
    src: "/images/purplehouse.jpg",
    alt: "Purple House, Bagbazar — home of Arabica",
    width: 1400,
    height: 933,
    category: "exterior",
  },
  {
    id: "18",
    src: "/images/header.webp",
    alt: "Arabica on opening day",
    width: 1400,
    height: 700,
    category: "exterior",
  },
];
